# Settings for "Images can be referenced only from allowed registries" policy, see more in "policies.md"
images-can-be-referenced-only-from-allowed-registries:
  # List of allowed repositories
  repos: ["", "bitnami"]