# Settings for "Images can be referenced only from allowed registries" policy, see more in "policies.md"
images-can-be-referenced-only-from-allowed-registries:
  # List of allowed repositories
  repos: ["", "harbor-trusted-org.local/", "harbor-partially-trusted-org.local/trusted_repo/"]

# Specifies alpine image with its repository and sha256 hash for security test
# Organizations that dont trust public registries and have "outside world" blocked
# should set this setting to their trusted repository that contains alpine image
# Valid image is not necessary for security test, but can be useful for exec into risky pod for educational purposes
alpineImage: "alpine@sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d"

# Specifies alpine image with its repository without tag for security test
# Organizations that dont trust public registries and have "outside world" blocked
# should set this setting to their trusted repository that contains alpine image
# Valid image is not necessary for security test, but can be useful for exec into risky pod for educational purposes
alpineImageEmptyTag: "alpine"

# Specifies alpine image with its repository and tag for security test
# Organizations that dont trust public registries and have "outside world" blocked
# should set this setting to their trusted repository that contains alpine image
# Valid image is not necessary for security test, but can be useful for exec into risky pod for educational purposes
alpineImageTagReferenced: "alpine:3.17"

# OCI registry for pulling kubewarden policies
ociRegistry: "ghcr.io/mcaniga"

# Specifies version of PSS that will be enforced using PSAC
pssVersion: v1.26

# Specifies version of Kyverno
kyvernoVersion: release-1.7

# Specifies version of OPA Gatekeeper
gatekeeperVersion: release-3.11

# Specifies versions of Kubewarden components
kubewarden:
  certManager: v1.11.1
  crds: 1.3.0 
  controller: 1.5.0
  defaults: 1.6.0