apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: alwayspullimagefromremoteregistry
  annotations:
    metadata.gatekeeper.sh/title: Always pull image from remote registry
    description: >-
      This policy validates the imagePullPolicy is set to `Always`.
      With `Always`, image is pulled from remote registry if local registry does not contain image with matching digest.
      Pulling from remote registry is prefered from security standpoint, local registry can be easier compromised in most cases.
spec:
  crd:
    spec:
      names:
        kind: AlwaysPullImageFromRemoteRegistry
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          description: >-
            This policy validates the imagePullPolicy is set to `Always`.
            With `Always`, image is pulled from remote registry if local registry does not contain image with matching digest.
            Pulling from remote registry is prefered from security standpoint, local registry can be easier compromised in most cases.
          properties:
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package alwaysPullImageFromRemoteRegistry

        violation[{"msg": msg, "details": {}}] {
            container := input.review.object.spec.containers[_]
            not container["imagePullPolicy"]
            msg := sprintf("container <%v> has not set imagePullPolicy to Always", [container.name])
        }

        violation[{"msg": msg, "details": {}}] {
          container := input.review.object.spec.containers[_]
          container.imagePullPolicy != "Always"
          msg := sprintf("container <%v> has not set imagePullPolicy to Always", [container.name])
        }