apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: image-can-be-referenced-only-with-image-digest
  annotations:
    metadata.gatekeeper.sh/title: Image can be referenced only with image digest
    description: >-
      This policy validates that the image is referenced with digest.
      Attacker can poison local registry, compromising image with same tag, thus malicious image can be loaded. 
      Instead of using tags, images should be referenced by digest. 
spec:
  crd:
    spec:
      names:
        kind: ImageCanBeReferencedOnlyWithImageDigest
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          description: >-
            This policy validates that the image is referenced with digest.
            Attacker can poison local registry, compromising image with same tag, thus malicious image can be loaded. 
            Instead of using tags, images should be referenced by digest. 
          properties:
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package imageCanBeReferencedOnlyWithImageDigest

        violation[{"msg": msg, "details": {}}] {
          container := input.review.object.spec.containers[_]
          not container.securityContext
          container.securityContext.readOnlyRootFilesystem == false
          msg := sprintf("container  <%v> must reference image by digest", [container.name])
        }