apiVersion: v1
kind: Pod
metadata:
  name: add-kill-capability
  annotations:
    readableName: Pod without dropped capabilities, but added kill capability
    vulnerabilityReason: Container process can kill other processes. 
spec:
  containers:
    - name: secure
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
          add:
            - "KILL"
        seccompProfile:
          type: "RuntimeDefault"