apiVersion: v1
kind: Pod
metadata:
  name: cpu-limits-are-not-set
  annotations:
    readableName: Container without set CPU limits
    vulnerabilityReason: Container can consume all of host CPU cores, and cause resource starvation for other pods.
spec:
  containers:
    - name: cpu-limits-are-not-set-container
      image: alpine@sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d # alpine 3.17.3
      imagePullPolicy: Always
      command: [ "sh", "-c", "sleep 1h" ]      
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"