apiVersion: v1
kind: Pod
metadata:
  name: cpu-requests-are-not-set
  annotations:
    readableName: Container without set CPU requests
    vulnerabilityReason: If CPU requests are not set, other misbehaving pod can cause resource starvation for this pod.
spec:
  containers:
    - name: cpu-requests-are-not-set-container
      image: <<alpineImage>> 
      imagePullPolicy: Always
      command: [ "sh", "-c", "sleep 1h" ]      
      readinessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 15
        periodSeconds: 20
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        # cpu limit was also deleted, because requests will default to limits when not provided
        limits:
          memory: "8000M" # in megabytes
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsUser: 10000
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"