apiVersion: v1
kind: Pod
metadata:
  name: cpu-requests-are-not-set
  annotations:
    readableName: Container without set CPU requests
    vulnerabilityReason: If CPU requests are not set, other misbehaving pod can cause resource starvation for this pod.
spec:
  containers:
    - name: cpu-requests-are-not-set-container
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"