apiVersion: v1
kind: Pod
metadata:
  name: drop-capabilities
  annotations:
    readableName: Pod without dropped capabilities
    vulnerabilityReason: Compromised container process will have default parts of root permissions (capabilities)
spec:
  containers:
    - name: drop-capabilities-container
      image: alpine@sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d # alpine 3.17.3
      imagePullPolicy: Always
      command: [ "sh", "-c", "sleep 1h" ]      
      readinessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 15
        periodSeconds: 20
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsUser: 10000
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"