apiVersion: v1
kind: Pod
metadata:
  name: drop-capabilities
  annotations:
    readableName: Pod without dropped capabilities
    vulnerabilityReason: Compromised container process will have default parts of root permissions (capabilities)
spec:
  containers:
    - name: drop-capabilities-container
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"