apiVersion: v1
kind: Pod
metadata:
  name: image-pull-policy-if-not-present
  annotations:
    readableName: Container has imagePullPolicy set to IfNotPresent
    vulnerabilityReason: Attacker can poison local registry, thus malicious image will be loaded.
spec:
  containers:
    - name: image-pull-policy-if-not-present-container
      image: <<alpineImage>> 
      imagePullPolicy: IfNotPresent
      command: [ "sh", "-c", "sleep 1h" ]      
      readinessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 15
        periodSeconds: 20
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsUser: 10000
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"