apiVersion: v1
kind: Pod
metadata:
  name: image-pull-policy-never
  annotations:
    readableName: Container has imagePullPolicy set to Never
    vulnerabilityReason: Attacker can poison local registry, thus malicious image will be loaded.
spec:
  containers:
    - name: cpu-limits-are-not-set-container
      image: alpine@sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d # alpine 3.17.3
      imagePullPolicy: Never
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"