apiVersion: v1
kind: Pod
metadata:
  name: memory-requests-are-not-set
  annotations:
    readableName: Container without set memory requests
    vulnerabilityReason: If memory requests are not set, other misbehaving container can cause resource starvation for this pod.
spec:
  containers:
    - name: memory-requests-are-not-set-container
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"