apiVersion: v1
kind: Pod
metadata:
  name: mount-host-path
  annotations:
    readableName: Pod with host mount
    vulnerabilityReason: Host mount exposes files or directories from host filesystem. Attacker can read, modify or delete this information from container (only read if readOnly). Violates all three attributes of CIA triad (only confidentiality if readOnly).
spec:
  containers:
    - name: mount-host-path-container
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      volumeMounts:
      - mountPath: /dummy
        name: hostpath-volume
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"
  volumes:
  - name: hostpath-volume
    hostPath:
      # directory location on host
      path: /var/run/docker.sock
      type: Directory