apiVersion: v1
kind: Pod
metadata:
  name: pid-namespace-sharing
  annotations:
    readableName: Pod with shared PID namespace
    vulnerabilityReason: Container process has access to host processes and can potentially manipulate with them. 
spec:
  hostPID: true
  containers:
    - name: pid-namespace-sharing-container
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"