apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-is-not-set
  annotations:
    readableName: Container has not set readiness probe
    vulnerabilityReason: Without readiness probe, traffic will be sent to pod that is just inicializing, causing undesirable behaviour.
spec:
  containers:
    - name: readiness-probe-is-not-set-container
      image: alpine@sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d # alpine 3.17.3
      imagePullPolicy: Always
      command: [ "sh", "-c", "sleep 1h" ]      
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"