apiVersion: v1
kind: Pod
metadata:
  name: run-as-nonroot-false
  annotations:
    readableName: Pod with runAsNonRoot field set to false.
    vulnerabilityReason: Processes will be run under root user
spec:
  containers:
    - name: run-as-nonroot-false-container
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: false
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"