apiVersion: v1
kind: Pod
metadata:
  name: run-as-nonroot-false
  annotations:
    readableName: Pod with runAsNonRoot field set to false.
    vulnerabilityReason: Processes will be run under root user
spec:
  containers:
    - name: secure
      image: ubuntu
      command: [ "sh", "-c", "sleep 1h" ]
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: false
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"