apiVersion: v1
kind: Pod
metadata:
  name: run-as-zero
  annotations:
    readableName: Pod with runAsUser field set to zero.
    vulnerabilityReason: Processes will be run under root user
spec:
  containers:
    - name: run-as-zero-container
      image: alpine@sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d # alpine 3.17.3
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsUser: 0
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "RuntimeDefault"