apiVersion: v1
kind: Pod
metadata:
  name: unconfined-seccomp-type
  annotations:
    readableName: Pod without disabled seccomp via Unconfined seccomp type
    vulnerabilityReason: Seccomp filters configured system calls. Disabling seccomp allows unrestricted access to system calls for container processes.
spec:
  containers:
    - name: unconfined-seccomp-type
      image: <<alpineImage>> 
      imagePullPolicy: Always
      command: [ "sh", "-c", "sleep 1h" ]      
      readinessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 15
        periodSeconds: 20
      resources:
        # minimum requirements for node resources, these resources will be reserved for pod lifetime
        requests:
          memory: "200M" # in megabytes
          cpu: "0.1" # in CPU cores
        # maximum resources that will node allocate for this container, these resources will not reserved for pod lifetime
        limits:
          memory: "8000M" # in megabytes
          cpu: "8" # in CPU cores
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsUser: 10000
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: "Unconfined"