apiVersion: v1
kind: Pod
metadata:
  name: without-security-context
  annotations:
    readableName: Pod without any security context or security settings.
    vulnerabilityReason: It is possible to deploy pod to your cluster without any security settings or security settings
spec:
  containers:
    - name: without-security-context-container
      image: alpine
      command: [ "sh", "-c", "sleep 1h" ]      
      readinessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        exec:
          command:
          - echo
          - ready
        initialDelaySeconds: 15
        periodSeconds: 20