apiVersion: v1
kind: Pod
metadata:
  name: without-security-context
  annotations:
    readableName: Pod without any security context.
    vulnerabilityReason: It is possible to deploy pod to your cluster without any security settings
spec:
  containers:
    - name: without-security-context
      image: alpine
      command: [ "sh", "-c", "sleep 1h" ]