apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AlwaysPullImageFromRemoteRegistry
metadata:
  name: always-pull-image-from-remote-registry-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]