apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ImageCanBeReferencedOnlyWithImageDigest
metadata:
  name: image-can-be-referenced-only-with-image-digest
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]