apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ImagesCanBeReferencedOnlyFromAllowedRegistries
metadata:
  name: imagescanbereferencedonlyfromallowedregistries
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]