apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ImagesCanBeReferencedOnlyFromAllowedRegistries
metadata:
  name: images-can-be-referenced-only-from-allowed-registries
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]