apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LimitsAndRequestsAreRequired
metadata:
  name: limitsandrequestsarerequired
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]