apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LimitsAndRequestsAreRequired
metadata:
  name: limits-and-requests-are-required
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]