apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RootFilesystemIsReadOnly
metadata:
  name: root-filesystem-is-readonly-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]