apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ReadinessProbesAreRequired
metadata:
  name: readinessprobesarerequired
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
      - {key:  kubernetes.io/metadata.name, operator: In, values: [<<namespace>>]}
    scope: "Namespaced"