apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: image-can-be-referenced-only-with-image-digest
spec:
  module: file://../wasm/image-can-be-referenced-only-with-image-digest.wasm
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  mutating: false