apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: limits-and-requests-are-required
  annotations:
    policies.kyverno.io/title: Limits and requests are required
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy validates that all containers have set memory and CPU requests and limits.
      Resource requests prevents resource starvation of the pod, if other pods on node are misbehaving.
      Resource limits specifies maximum quantity of resources that can be aquired by given container, defending other pods from resource starvation.
      Only presence of settings is checked, can be set to arbitrary value.

spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: limits-and-requests-are-required-rule
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - <<namespace>>
    validate:
      message: "CPU and memory resource requests and limits are required."
      pattern:
        spec:
          containers:
          - resources:
              requests:
                memory: "?*"
                cpu: "?*"
              limits:
                memory: "?*"
                cpu: "?*"