apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: readiness-probes-are-required
  annotations:
    policies.kyverno.io/title: Readiness probes are required
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy validates that all containers contain readinessProbe field.
      Without readiness probe, traffic will be sent to pod that is just inicializing, causing undesirable behaviour.
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: readiness-probes-are-required-rule
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Readiness probes are required for all containers."
      foreach:
      - list: request.object.spec.containers[]
        deny:
          conditions:
            all:
            - key: readinessProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"